
//! Autogenerated weights for `pallet_ipf`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-05-23, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/invarch-collator
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet-ipf
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --json-file=node/res/brainstorm-raw.json
// --output
// ../InvArch-Frames/INV4/pallet-ipf/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_ipf`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_ipf::WeightInfo for WeightInfo<T> {
	// Storage: Ipf NextIpfId (r:1 w:1)
	// Storage: Ipf IpfByOwner (r:0 w:1)
	// Storage: Ipf IpfStorage (r:0 w:1)
	fn mint() -> Weight {
		(17_563_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: Ipf IpfStorage (r:1 w:1)
	// Storage: Ipf IpfByOwner (r:0 w:1)
	fn burn() -> Weight {
		(17_272_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}
